/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab01;

public class App {
    
    public static String pluralize(String wor , int num)
    {
        if(num <= 1){
            return wor;
        }else {
            return wor+'s';
        }
    }


    public static void main(String[] args) {

        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");
    }
}
