/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        try {
        Restaurant malek = new Restaurant("Malek",5,10);
        System.out.println(malek.toString());

        Review firstRe = new Review("goood foood","mike",4);
            System.out.println(firstRe.toString());

        }catch (Exception ex){
            System.out.println("Error: "+ex);
        }
    }
}
