/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static int readSimColon(String filePath){
        // Getting the file path
        Path path = Paths.get(filePath);
        BufferedReader reader = null; //Define the reader
        String missingSemiolon= "";
            int currentLine = 1;
        int missedSemiColonsCounter = 0;
        try{
            // Assign the reader with the file path
            reader = Files.newBufferedReader(path);
            String line = reader.readLine();
            while(line != null) {
                if (line.contains(";") ||line.isEmpty()||line.startsWith("/") || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else") ) {

                }
                else{
                    missingSemiolon+="Line " + currentLine + ": Missing semicolon.\n";
                    missedSemiColonsCounter += 1;
                }
                    currentLine++;
                    line = reader.readLine();
            }
        }catch (IOException ex){
            ex.printStackTrace();
        }finally {
            if(reader != null) {
                try {
                    reader.close();
                } catch(IOException e){
                    System.out.println("an error occurred while closing the file");
                }
            }
        }
        if(missingSemiolon == ""){
            missingSemiolon+= "There is not any missing for semicolon in the file "+filePath.substring(filePath.lastIndexOf("\\")+1)+"\n";
            System.out.println(missingSemiolon);
        }else {
            missingSemiolon+= "The line(s) above are missing from semicolon in the file "+filePath.substring(filePath.lastIndexOf("\\")+1)+"\n";
            System.out.println(missingSemiolon);

        }
        return missedSemiColonsCounter;
    }

    public static void main(String[] args) {

//        System.out.println(readSimColon());

        System.out.println(readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js"));
        System.out.println(readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\noError.js"));
        System.out.println(readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\fewErrors.js"));
        System.out.println(readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\oneError.js"));
        System.out.println(readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\emptyFile.js"));


    }
}
