/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

@Test public void testReadSimColon(){
    int testNoError =  App.readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\noError.js");
//    System.out.println(testNoError);
    int one = App.readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\oneError.js");
    int few = App.readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\fewErrors.js");
    int many = App.readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js"); // This is for many Errors
    int empty = App.readSimColon("C:\\Users\\malik\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\emptyFile.js");

    assertEquals("The testing of missing for semicolon in the file noError.js",0,testNoError);
    assertEquals("The testing of missing for semicolon in the file oneError.js",1,one);
    assertEquals("The testing of missing for semicolon in the file fewError.js",2,few);
    assertEquals("The testing of missing for semicolon in the file manyError.js",42,many);
    assertEquals("The testing of missing for semicolon in the file emptyFile.js",0,empty);


}
}
